image: docker:18-git

services:
  - docker:18-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  PROJECT_NAME: connect-f7e5b
  GCR_HOST: eu.gcr.io
  CONTAINER_IMAGE: registry.gitlab.et-ns.net/$CI_PROJECT_PATH
  CONTAINER_IMAGE_TEST: registry.gitlab.et-ns.net/$CI_PROJECT_PATH/test
  CONTAINER_IMAGE_GCR: $GCR_HOST/$PROJECT_NAME/$CI_PROJECT_PATH
  VERSION: $CI_COMMIT_SHA

stages:
  - build
  - test
  - tag
  - deploy staging
  - deploy production

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_image:
  stage: build
  tags:
    - build
  script:
    - docker pull $CONTAINER_IMAGE:$CI_COMMIT_SHA || true
    - docker build --cache-from $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
