# .github/workflows/chromatic.yml

# Workflow name
name: "Test and Chromatic Deployment"

# Event for the workflow
on: push

defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn docker-test
  chromatic:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: run chromatic
        run: yarn chromatic
